### ISSUE TITLE
icon(d,map) function from dc.leafletMarkerChart not usable

### ISSUE THREAD

**Issue by PBrockmann** [Intellipharm/dc-addons#8]
d and map are undefined

`
.icon(function(d,map) {
   console.log(d);
}
`

How can I change the color of the icon then ?

**Comment by gordonwoodhull** [comment]
Looks like _marker() a few lines up just needs to pass this stuff through - `_icon()` should be `_icon(d,map)`. 

dc.leaflet.js has inherited the same mistake, will file an issue there too.

**Comment by Tim-Intellipharm** [comment]
Fixed in commit 5d793530ef880c2567b93a7a6241502da1f2976b and released in [v0.13.0](https://github.com/Intellipharm/dc-addons/releases/tag/v0.13.0).

@gordonwoodhull You were right. A few lines up I needed to add the arguments to the function call. However the map variable in the `_marker` function was undefined. So what I ended up doing was calling it like so `_icon(d, _chart.map())`

**Comment by PBrockmann** [comment]
Thanks for the quick correction. It works nicelly.
![dc leaflet_icon](https://cloud.githubusercontent.com/assets/5402758/14369925/5d63c0b6-fd29-11e5-9abc-de253baca7c5.png)
